# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 94dbfd39dc8b908d85511808a89df07ca4f0ef292dbb66533f0e7982dd5be568d466d9f88685534506902cafb5689181914cb917e4f077abc0b99cc24e90c07b

test:
  secret_key_base: 42fea5d802dcaf460091c22796fa148c04f911412db57e31d665b60002272e51012ca27977b8a2db2c6632bb505a9dd83175c10f2546953ec251c12f8167a00f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
